channels:
  - conda-forge

dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - beautifulsoup4
  - openpyxl
  - requests
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pip:
    - rpaframework==28.5.1        # https://rpaframework.org/releasenotes.html
    - robocorp==1.6.2             # https://pypi.org/project/robocorp
    - robocorp-browser==2.2.2     # https://pypi.org/project/robocorp-browser
    - robocorp-excel==0.4.2       # https://pypi.org/project/robocorp-excel

