channels:
  - conda-forge

dependencies:
  - python=3.9                # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - beautifulsoup4
  - openpyxl
  - requests
  - pip:
    - rpaframework==28.5.1        # https://rpaframework.org/releasenotes.html

